#!/bin/sh /etc/rc.common

#service startup sequence
#start after shadowsocks
START=95
#stop before shadowsocks
STOP=10

USE_PROCD=1
NAME=goquiet

uci_get_by_type() {
	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
	echo ${ret:=$3}
}

gen_config_file() {
	local config_file=/var/etc/$NAME.json
	cat <<-EOF >$config_file
		{
		    "ServerName": "$(uci_get_by_type goquiet ServerName)",
		    "Key": "$(uci_get_by_type goquiet Key)",
		    "TicketTimeHint": $(uci_get_by_type goquiet TicketTimeHint),
		    "Browser": "$(uci_get_by_type goquiet Browser)"
		}
EOF
	echo $config_file
}


start_service() {
	local enable=$(uci_get_by_type goquiet enable)
	
	logger enable=$(uci_get_by_type goquiet enable)
	logger remoteIP=$(uci_get_by_type goquiet remoteIP)
	logger remotePort=$(uci_get_by_type goquiet remotePort)
	logger localPort=$(uci_get_by_type goquiet localPort)
	logger ServerName=$(uci_get_by_type goquiet ServerName)
	logger Key=$(uci_get_by_type goquiet Key)
	logger TicketTimeHint=$(uci_get_by_type goquiet TicketTimeHint)
	logger Browser=$(uci_get_by_type goquiet Browser)
	
	if [ $enable ]; then
		local remoteIP=$(uci_get_by_type goquiet remoteIP)
		local remotePort=$(uci_get_by_type goquiet remotePort)
		local localPort=$(uci_get_by_type goquiet localPort)

		procd_open_instance
		procd_set_param command gq-client
		procd_append_param command -s $remoteIP
		procd_append_param command -p $remotePort
		procd_append_param command -l $localPort
		procd_append_param command -c $(gen_config_file)

		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param user nobody
	
		procd_close_instance
	fi
}